- name: Create a New Project in OpenShift Enterprise 3
  hosts: all
  gather_facts: false
  connection: ssh
  tasks:
    - name: Creando a New Project in OpenShift Enterprise 3
      command: oadm new-project {{project_name}} --display-name="Test Project {{project_name}}." --admin=demo --node-selector='host=apps'
    
    - name: Status of OpenShift Enteprise 3
      command: oc status
