- name: Delete a Project in OpenShift Enterprise 3
  hosts: all
  gather_facts: false
  connection: ssh
  tasks:
    - name: Deleting a Project in OpenShift Enterprise 3
      command: oc delete project "{{ project_name }}"
