- name: Creando Aplicación RH Forum 2016 en OpenShift Enterprise 3.2
  hosts: all
  gather_facts: false
  connection: ssh
  tasks:
    - name: Creando Proyecto RH Forum 2016 en OpenShift Enterprise 3.2
      command: oadm new-project {{project_name}} --display-name="Red Hat Forum {{demo_environment}}." --admin={{demo_user}} --node-selector='host=apps'

    - name: Creando nueva Aplicacion RH Forum 2016 en OpenShift Enterprise 3.2
      command: oc new-app forum-apps --namespace={{project_name}}

    - name: Asignando Permisos para cicd al nuevo Projecto 
      command: oc policy add-role-to-user edit system:serviceaccount:cicd:default -n {{project_name}}

    - name: Asignando Permisos para tooling al nuevo Projecto
      command: oc policy add-role-to-user edit system:serviceaccount:tooling:default -n {{project_name}}

    - name: Configurando Auto-Scaling para HotelsWS
      command: oc autoscale dc/hotels --min 1 --max 5 --cpu-percent=5 -n {{project_name}}
